### ISSUE TITLE
Visual Studio build errors

### ISSUE THREAD

**Issue by edsilv** [dbradleyfl/Mixed-Reality-JS#1]
> To deploy and debug, on emulator or device, run mrjs package, open the HoloJS solution located in the release/ folder in Visual Studio. Change the deployment app from HoloHost to ThreeJSApp (right click ThreeJSApp in Solution Exporer and click "set as StartUp project"). Build > Clean Solution. Build > Rebuild Solution. Select your deployment target (Device, or emulator) in the menu then deploy the ThreeJSApp.

I tried this in VS 2017 and got these errors:

![image](https://cloud.githubusercontent.com/assets/1334393/24840683/48832b26-1d69-11e7-844a-81430fc8d2f0.png)

Looks like VersionHelpers.h is missing?

**Comment by dbradleyfl** [comment]
Looks like the ANGLE library is missing. 

Part of the "mrjs package" process is cloning down HoloJS [with the --recursive](https://github.com/dbradleyfl/Mixed-Reality-JS/blob/master/bin/mrjs.js#L63) option to get it's sub modules (ANGLE). The command can take quite a while to complete. Did you make sure to wait for it to finish before you opened the project in visual studio?

You could also delete the release folder and run "mrjs package" again to see if we get the same error.

**Comment by edsilv** [comment]
@dbradleyfl Hi, I tried running the setup steps again in a new project. It all seemed to clone successfully. I then cleaned and rebuilt, which gave me this message:

![1](https://cloud.githubusercontent.com/assets/1334393/24853121/e9d2c99c-1dd1-11e7-94a2-c4756098f9d9.jpg)

I retargeted the solution:

![2](https://cloud.githubusercontent.com/assets/1334393/24853126/f560f018-1dd1-11e7-9b54-04ff7574a474.jpg)

Which appeared to be successful. I then tried another build and got the same errors as before:

![3](https://cloud.githubusercontent.com/assets/1334393/24853156/0d8cbfd2-1dd2-11e7-9a5f-0e0d39b7621b.jpg)

**Comment by dbradleyfl** [comment]
Interesting. I'm going to upgrade to VS 2017 and try and figure it out. I'll get back to you ASAP.

**Comment by dbradleyfl** [comment]
@edsilv HoloJS [suggests /  requires using Visual Studio 2015](https://github.com/Microsoft/HoloJS#build-the-sample), thus it seems we might be required to use it for Mixed Reality JS at the moment. I'll continue looking into solving this issue. In the meantime I will edit the readme to reflect that Visual Studio 2015 as a requirement. Thanks again.

**Comment by edsilv** [comment]
@dbradleyfl I just tried deleting release and running `mrjs package` again and it's now working in VS2017. Looks like neither HoloJS or ANGLE have been updated in the meantime. It must be something that's changed about my setup, although difficult to know exactly what...

**Comment by dbradleyfl** [comment]
Glad to see you got it figured out (by unknown means). Maybe VS2017 had an update. Anyway, I'll call this issue closed for now.

@edsilv I'd love to see what you end up building with mrjs!
